export const Navigation = Object.freeze({
  AUTHNAVIGATOR: 'AuthNavigator',
  AUTH: 'Auth',
  LOGIN: 'Login',
  REGISTER: 'Register',
  APPNAVIGATOR: 'AppNavigator',
  BILLNAVIGATOR: 'BillNavigator',
  BILLS: 'Bills',
  BILLDETAIL: 'BillDetail',
  EDITPEOPLE: 'EditPeople',
  EDITITEMS: 'EditItems',
  SCANNAVIGATOR: 'ScanNavigator',
  SCAN: 'Scan',
  ADDPEOPLE: 'AddPeople',
  ADDITEMS: 'AddItems',
  ACCEPTRESULT: 'AcceptResult',
  SETTINGS: 'Settings',
})